default:
  counts:
    synID: syn22084837
    version:
    gene id: feature
  metadata:
    synID: syn22090070
    version: 2
    sample id: sampleID
  biomart:
    synID: syn21907998
    version:
    filters: ensembl_gene_id
    host: ensembl.org
    organism: hsa
  factors: ["sampleID", "batch", "sex", "diagnosis"]
  continuous: ["RIN", "pmi", "ageofdeath"]
  x_var: diagnosis
  conditions: ["diagnosis", "sex"]
  cpm threshold: 1
  percent threshold: 0.5
  sex check: sex
  dimensions:
    color: "diagnosis"
    shape: "batch"
    size: "ageofdeath"
  skip model: TRUE
  force model with: ["sex", "diagnosis", "batch"]
  de log2FC: 1.5
  de p-value threshold: 0.05
  de contrasts:
    diagnosis: ["diagnosis"]
    diagnosis-sex: ["diagnosis-sex"]
  report: "openSci"
  store output: syn23572479
