default:
  analysis title: openSci
  counts:
    synID: syn22084837
    version:
    gene id: feature
  metadata:
    synID: syn22090070
    version: 2
    sample id: sampleID
  biomart:
    synID: syn21907998
    version:
    filters: ensembl_gene_id
    host: ensembl.org
    organism: hsa
  factors: ["sampleID", "RIN", "batch", "sex", "diagnosis"]
  continuous: ["pmi", "ageofdeath"]
  x_var: diagnosis
  conditions:
    sex-diagnosis interaction: ["diagnosis", "sex"]
    diagnosis: ["diagnosis"]
    sex: ["sex"]
  sex check: sex
