default:
  counts:
    synID: syn21587392
    version: 1
  metadata:
    synID: syn21587404
    version: 3
  biomart:
    synID: syn21907998
    version:
  factors:
  continuous:
  sample:
mayo:
  counts:
    synID: syn21587392
    version: 2
  metadata:
    synID: syn21587404
    version: 4
  biomart:
    synID: syn21907998
    version:
  factors: [ "donorid", "sampleid", "source", "sex", "flowcell", "diagnosis", "source_tissue_diagnosis", "tissue_diagnosis", "tissue_APOE4" ]
  continuous: [ "rin", "rin2", "age_death", "pct_pf_reads_aligned",
                "pct_coding_bases", "pct_intergenic_bases", "pct_intronic_bases",
                "pct_ribosomal_bases" ] #pmi missing at the moment
  gene id: feature
  sample: sampleid


