default:
  counts:
    synID: syn21587392
    version: 1
  metadata:
    synID: syn21587404
    version: 2
  factors:
  continuous:
  sample:
mayo:
  counts:
    synID: syn21587392
    version: 1
  metadata:
    synID: syn21587404
    version: 2
  factors: [ "donorid", "source", "sex", "flowcell", "tissue_source_diagnosis", "tissue_diagnosis", "tissue_apoe4" ]
  continuous: [ "rin", "rin2", "age_death", "pmi", "pct_pf_reads_aligned",
                "pct_coding_bases", "pct_intergenic_bases", "pct_intronic_bases",
                "pct_ribosomal_bases" ]
  sample: sampleid


