library(CovariateAnalysis) # get the package from devtools::install_github('th1vairam/CovariateAnalysis@dev')
library(data.table)
library(plyr)
library(tidyverse)
library(psych)
library(limma)
library(edgeR)
library(biomaRt)
library(RColorBrewer)
library(cqn)
library(synapser)
library(knitr)
##library(doParallel) Need to figure out how to parrallelize drake workflows
library(foreach)
##cl = makeCluster(detectCores()-2)
##registerDoParallel(cl)