library(config)
library(CovariateAnalysis)
library(data.table)
library(plyr); library(dplyr)
library(tidyverse)
library(psych)
library(limma)
library(edgeR)
library(biomaRt)
library(RColorBrewer)
library(cqn)
library(synapser)
library(knitr)
library(foreach)
library(drake)
library(tibble)
library(GenomicRanges)
